# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###
GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
  "name": "test",
  "pwd": "test",
  "email": "a@b.de"
}

###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
  "email": "a@b.de",
  "pwd": "test"
}


###
POST https://teamboard.server-welt.com:8000/register/
Content-Type: application/json

{
  "name": "test",
  "pwd": "test",
  "email": "inf21012@lehre.dhbw-stuttgart.de"
}
